# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-23 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200122_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='title',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='category',
            field=models.CharField(choices=[('Blog', 'blog'), ('Jurnal', 'jurnal'), ('Berita', 'berita')], default='Blog', max_length=20),
        ),
    ]
