# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-23 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200123_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='category',
        ),
    ]
