# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-24 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('P', 'pria'), ('W', 'wanita')], max_length=20),
        ),
    ]
