# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-20 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_artikel_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikel',
            name='photo',
        ),
    ]
