# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-23 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_artikel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='kategori',
            field=models.CharField(choices=[('Blog', 'blog'), ('Jurnal', 'jurnal'), ('Berita', 'berita')], default='Blog', max_length=20),
        ),
    ]
